name = "OSF"
uuid = "543d4c35-cc35-473a-a1e5-1d12b41c9fba"
authors = ["Zaki A <zaki@live.ca> and contributors"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
DataStructures = "^0.18"
HTTP = "^0.9"
JSON = "^0.21"
julia = "^1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
